import "~/styles/globals.css";
import "@uploadthing/react/styles.css"

import { ClerkProvider } from "@clerk/nextjs";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "t3gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
      <body className={`font-sans ${GeistSans.variable} dark`}>
        <div className="h-screen grid grid-rows-[auto,1fr]">
          <TopNav />
          <main className="overflow-y-scroll">
            {children}
          </main>
        </div>
        {modal}
        <div id="modal-root" />
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
